clc;
clear;
xn=input('Enter the sequence x(n) in a row matrix form:');
xs=input('Enter the starting point of x(n):');
xe=xs+length(xn)-1;
nx=xs:xe;
subplot(3,1,1);
stem(nx,xn,'-ok','linewidth',2);
xlabel('n');
ylabel('x(n)');
title('x(n)');
grid on;
h1n=input('Enter the sequence h1(n) in a row matrix form:');
h1s=input('Enter the starting point of h1(n):');
h1e=h1s+length(h1n)-1;
nh1=h1s:h1e;
subplot(3,1,2);
stem(nh1,h1n,'-ok','linewidth',2);
xlabel('n');
ylabel('h1(n)');
title('h1(n)');
grid on;
h2n=input('Enter the sequence h2(n) in a row matrix form:');
h2s=input('Enter the starting point of h2(n):');
h2e=h2s+length(h2n)-1;
nh2=h2s:h2e;
subplot(3,1,3);
stem(nh2,h2n,'-ok','linewidth',2);
xlabel('n');
ylabel('h2(n)');
title('h2(n)');
grid on;
yn=conv(xn,conv(h1n,h2n));
ys=xs+h1s+h2s;
ye=xe+h1e+h2e;
ny=ys:ye;
subplot(2,1,2);
stem(ny,yn,'-ok','linewidth',2);
xlabel('n');
ylabel('y(n)');
title('y(n)=x(n)*(h1(n)*h2(n))');
grid on;
y1n=conv(conv(xn,h1n),h2n);
y1s=xs+h1s+h2s;
y1e=xe+h1e+h2e;
ny1=y1s:y1e;
subplot(2,1,2);
stem(ny1,y1n,'-ok','linewidth',2);
xlabel('n');
ylabel('y(n)');
title('y(n)=(x(n)*h1(n))*h2(n)');
grid on;