clc;
clear;
xn=input('Enter the sequence x(n) in a row matrix form:');
xs=input('Enter the starting point of x(n):');
xe=xs+length(xn)-1;
nx=xs:xe;
subplot(3,1,1);
stem(nx,xn,'-ok','linewidth',2);
xlabel('n');
ylabel('x(n)');
title('x(n)');
grid on;
hn=input('Enter the sequence h(n) in a row matrix form:');
hs=input('Enter the starting point of h(n):');
he=hs+length(hn)-1;
nh=hs:he;
subplot(3,1,2);
stem(nh,hn,'-ok','linewidth',2);
xlabel('n');
ylabel('h(n)');
title('h(n)');
grid on;
yn=conv(xn,hn);
ys=xs+hs;
ye=xe+he;
ny=ys:ye;
subplot(3,1,3);
stem(ny,yn,'-ok','linewidth',2);
xlabel('n');
ylabel('y(n)');
title('y(n)');
grid on;