clc;
clear;
xn=input('Enter the sequence x(n) in a row matrix form:');
xs=input('Enter the starting point of x(n):');
xe=xs+length(xn)-1;
nx=xs:xe;
subplot(5,1,1);
stem(nx,xn,'-ok','linewidth',2);
xlabel('n');
ylabel('x(n)');
title('x(n)');
grid on;
h1n=input('Enter the sequence h1(n) in a row matrix form:');
h1s=input('Enter the starting point of h1(n):');
h1e=h1s+length(h1n)-1;
nh1=h1s:h1e;
subplot(5,1,2);
stem(nh1,h1n,'-ok','linewidth',2);
xlabel('n');
ylabel('h1(n)');
title('h1(n)');
grid on;
h2n=input('Enter the sequence h2(n) in a row matrix form:');
h2s=input('Enter the starting point of h2(n):');
h2e=h2s+length(h2n)-1;
nh2=h2s:h2e;
subplot(5,1,3);
stem(nh2,h2n,'-ok','linewidth',2);
xlabel('n');
ylabel('h2(n)');
title('h2(n)');
grid on;
an=h1n+h2n;
as=h1s+h2s;
ae=as+length(an)-1;
na=as:ae;

yn=conv(xn,an);
ys=xs+as;
ye=xe+ae;
ny=ys:ye;
subplot(2,1,1);
stem(ny,yn);
grid on;

bn=conv(xn,h1n);
bs=xs+h1s;
be=xe+h1e;
nb=bs:be;

cn=conv(xn,h2n);
cs=xs+h2s;
ce=xe+h2e;
nc=cs:ce;

dn=bn+cn;
ds=bs+cs-1;
de=ds+length(dn)-1;
nd=ds:de;
subplot(2,1,2);
stem(nd,dn);
grid on;